config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, controllers: { registrations: 'registrations' }
  post 'payments/create'
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]
  resources :products do
    resources :comments
  end
  post 'simple_pages/thank_you'
  get '/contact', to: 'simple_pages#contact'
  get '/about', to: 'simple_pages#about'
  get '/', to: 'simple_pages#index'
  root 'simple_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Euro Bike Tours</title>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('logo_left.png'), :rel => 'icon', :type =>  'image/png' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Exo" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kanit:300,500,700" rel="stylesheet">


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>

  <body>

    <button class="hamburger hamburger--collapse nav-open" type="button">
      <span class="hamburger-box">
        <span class="hamburger-inner"></span>
      </span>
    </button>

    <nav class="nav-container" role="navigation">
      <div class="primary-links-container">
        <div class="row primary-links-row no-gutters animated">
          <div class="col-md-4">
            <a href="/about#tour-types" class="nav-item h-100 w-100" id="nav-item-1">
              <div class="nav-item-overlay flex-column">
                <h2 class="overlay-header kanit-3 white no-margin">Tour Types</h2>
                <p class="hover-fadeUp white kanit-3 text-center">Can't decide between guided or self guided? Private or group? All is explained here.</p>
              </div>
            </a>
          </div>
          <div class="col-md-4">
            <a href="/products" class="nav-item h-100 w-100" id="nav-item-2">
              <div class="nav-item-overlay flex-column">
                <h2 class="overlay-header kanit-3 white no-margin">Explore Routes</h2>
                <p class="hover-fadeUp white kanit-3 text-center">Where would you like to go? Browse the full range of tours and locations on offer.</p>
              </div>
            </a>
          </div>
          <div class="col-md-4">
            <a href="/contact" class="nav-item h-100 w-100" id="nav-item-3">
              <div class="nav-item-overlay flex-column">
                <h2 class="overlay-header kanit-3 white no-margin">Contact Us</h2>
                <p class="hover-fadeUp white kanit-3 text-center">Questions? Get in touch :)</p>
              </div>
            </a>
          </div>
        </div> <!-- primary links row -->
      </div> <!-- primary links container -->
      <div class="secondary-links-container">
        <div class="row secondary-links-row no-gutters animated">
          <div class="col-md-6">
            <h2 class="nav-header kanit-3 blue text-center">Browse Euro Bike Tours</h2>
            <div class="nav-divider"></div>
            <div class="secondary-links-list d-flex flex-column text-center">
              <a href="/" class="secondary-link white kanit-3">Home</a>
              <a href="/about" class="secondary-link white kanit-3">About Us</a>
              <a href="/" class="secondary-link white kanit-3">FAQs</a>

              <% if user_signed_in? %>
                <%= link_to(destroy_user_session_path, method: :delete, class:"secondary-link white kanit-3") do %>
                  Log Out
                <% end %>
              <% else %>
                <%= link_to(new_user_session_path, class:"secondary-link white kanit-3") do %>
                  Log In
                <% end %>
              <% end %>

            </div>
          </div>
          <div class="col-md-6 d-flex flex-row justify-content-center align-items-center">
            <div class="d-flex justify-content-between">
              <a href="https://www.facebook.com" class="d-flex justify-content-center align-items-center social-icon" id="facebook">
                <i class="fab fa-facebook-f white"></i>
              </a>
              <a href="https://www.twitter.com" class="d-flex justify-content-center align-items-center social-icon" id="twitter">
                <i class="fab fa-twitter white"></i>
              </a>
                <a href="https://www.instagram.com" class="d-flex justify-content-center align-items-center social-icon" id="instagram">
                <i class="fab fa-instagram white"></i>
              </a>
                <a href="https://www.youtube.com" class="d-flex justify-content-center align-items-center social-icon" id="youtube">
                <i class="fab fa-youtube white"></i>
              </a>
            </div>
          </div>
        </div> <!-- secondary-links-row -->
      </div> <!-- secondary links container -->
    </nav>

    <!-- Primary Navbar (=>1200px) -->
    <!-- <nav class="navbar navbar-inverse navbar-fixed-top primary-navbar" role="navigation">
      <i class="fas fa-bars" id="sidenav-open-btn"></i>
      <div class="title navbar-brand">
        <%= link_to root_path, id: 'home-link' do %>
          <h1>CYCLECiTy</h1>
        <% end %>
      </div>
      <div class="first-nav-container" id="navbar-container">
        <div class="navbar-inner">
          <ul class="nav navbar-nav" id="nav-list">
            <li class="hover-item"><%= link_to "Home", root_path %></li>
            <li class="hover-item"><%= link_to "Products", products_path %></li>
            <% if user_signed_in? %>
              <li class="hover-item"><%= link_to "Orders", orders_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="second-nav-container">
        <div class="nav-right">
          <li id="search-box">
            <%= form_with(url: products_path, method: 'get', local: true, class: 'navbar-form') do |form| %>
              <%= form.text_field :q, id: 'q', placeholder: 'Enter search term...', value: params[:q] %>
              <%= form.submit 'Search', id: 'search-btn' %>
            <% end %>
          </li>
            <% if user_signed_in? %>
              <%= link_to(destroy_user_session_path, method: :delete) do %>
                <button class="login-logout">Logout</button>
              <% end %>
            <% else %>
              <%= link_to(new_user_session_path) do %>
                <button class="login-logout">Login</button>
              <% end %>
            <% end %>
        </div>
      </div>
    </nav> -->


    <% if notice %>
      <div class="info-message">
        <div class="notice alert alert-success" role="alert"><%= notice %></div>
      </div>
    <% end %>
    <% if alert %>
      <div class="info-message">
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      </div>
    <% end %>

    <div class="body-content animated">
      <%= yield %>
    </div>

  </body>
</html>